version: '3.1'

services:

  db:
      image: mysql:latest
      deploy:
         restart_policy:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: inholland
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: mysql
      volumes:
        - ./sql-scripts:/docker-entrypoint-initdb.d/
      networks:
      - wimmelsoft  

  server:
       image: wimmelsoft/php-mysqli:0.2
       build: .
       depends_on:
         - db
       deploy:
         restart_policy:
           condition: on-failure
           delay: 5s
           max_attempts: 3
           window: 120s    
       ports:
         - 80:80
       networks:
          - wimmelsoft
       volumes:
          - ./src:/var/www/html
          - ./ini:/usr/local/etc/php/conf.d


  adminer:
     image: adminer
     restart: always
     ports:
       - 8080:8080
     networks:
       - wimmelsoft  
   
networks:
  wimmelsoft:
    driver: overlay
