version: '3.1'

services:

  db:
    image: mysql:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - php.env
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/
    networks:
      - php

  server:
    image: wimmelsoft/php-server:1.8.0
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 80:80
    env_file:
      - php.env
    networks:
      - php
    volumes:
      - "./src:/var/www/html"
      - "./include/apache2.conf:/etc/apache2/apache2.conf"
      - "./include/000-default.conf:/etc/apache2/sites-available/000-default.conf"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    env_file:
      - php.env
    networks:
      - php

networks:
  php:
    driver: overlay
