version: '3.1'

services:

  db:
    image: mysql:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: inholland
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      TZ: "Europe/Amsterdam"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/
    networks:
      - php

  server:
    image: wimmelsoft/php-server:1.8.1
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 80:80
    networks:
      - php
    environment:
      TZ: "Europe/Amsterdam"
      API_KEY: "<INSERT API_KEY HERE>"
    volumes:
      - "./cron/cron.php:/opt/scripts/cron.php"
      - ./src:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - php

networks:
  php:
    driver: overlay
